name: github-action
run-name: ${{ github.actor }} is out building GitHub Actions

on:
  push:
    # Pattern matched against refs/tags
    tags:        
      - '**' 

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build Maven Projects
        run: |
          mvn clean package -f ./user/pom.xml
          mvn clean package -f ./dispatch/pom.xml
          mvn clean package -f ./driver/pom.xml
          mvn clean package -f ./operationstatistics/pom.xml

      - name: Docker Build and push for User
        uses: docker/build-push-action@v4
        with:
          context: ./user
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/user:latest
            ghcr.io/${{ github.repository }}/user:${{ github.ref_name }}
            
      - name: Docker Build and push for Dispatch
        uses: docker/build-push-action@v4
        with:
          context: ./dispatch
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/dispatch:latest
            ghcr.io/${{ github.repository }}/dispatch:${{ github.ref_name }}
            
      - name: Docker Build and push for Driver
        uses: docker/build-push-action@v4
        with:
          context: ./driver
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/driver:latest
            ghcr.io/${{ github.repository }}/driver:${{ github.ref_name }}
            
      - name: Docker Build and push for Operationstatistics
        uses: docker/build-push-action@v4
        with:
          context: ./operationstatistics
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/operationstatistics:latest
            ghcr.io/${{ github.repository }}/operationstatistics:${{ github.ref_name }}
            
