server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
#<<< API Gateway / Routes
      routes:
        - id: user
          uri: http://localhost:8082
          predicates:
            - Path=/users/**, 
        - id: dispatch
          uri: http://localhost:8083
          predicates:
            - Path=/operations/**, /matchings/**, 
        - id: driver
          uri: http://localhost:8084
          predicates:
            - Path=/drivers/**, 
        - id: operationstatistics
          uri: http://localhost:8085
          predicates:
            - Path=, /operationRecords/**
        - id: frontend
          uri: http://localhost:8080
          predicates:
            - Path=/**
#>>> API Gateway / Routes
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: user
          uri: http://user:8080
          predicates:
            - Path=/users/**, 
        - id: dispatch
          uri: http://dispatch:8080
          predicates:
            - Path=/operations/**, /matchings/**, 
        - id: driver
          uri: http://driver:8080
          predicates:
            - Path=/drivers/**, 
        - id: operationstatistics
          uri: http://operationstatistics:8080
          predicates:
            - Path=, 
        - id: frontend
          uri: http://frontend:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
