server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
#<<< API Gateway / Routes
      routes:
        - id: payment
          uri: http://localhost:8032
          predicates:
            - Path=/payments/**, 
        - id: review
          uri: http://localhost:8052
          predicates:
            - Path=/reviews/**
        - id: reservation
          uri: http://localhost:8072
          predicates:
            - Path=/reservations/**, 
        - id: notification
          uri: http://localhost:8073
          predicates:
            - Path=/notifications/**
          filters:
            - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_FIRST
        - id: user
          uri: http://localhost:8082
          predicates:
            - Path=/users/**, 
        - id: dispatch
          uri: http://localhost:8083
          predicates:
            - Path=/operations/**, /matchings/**, 
        - id: driver
          uri: http://localhost:8084
          predicates:
            - Path=/drivers/**, 
        - id: operationstatistics
          uri: http://localhost:8085
          predicates:
            - Path=, /operationRecords/**
        - id: frontend
          uri: http://localhost:8080
          predicates:
            - Path=/**
#>>> API Gateway / Routes
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_FIRST
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            exposedHeaders:
              - "X-Total-Count"
              - "Link"
              - "Access-Control-Allow-Origin"
              - "Access-Control-Allow-Credentials"
            allowCredentials: true
            maxAge: 3600


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: payment
          uri: http://payment:8080
          predicates:
            - Path=/payments/**, 
        - id: review
          uri: http://review:8080
          predicates:
            - Path=/reviews/**
        - id: reservation
          uri: http://reservation:8080
          predicates:
            - Path=/reservations/**, 
        - id: notification
          uri: http://notification:8080
          predicates:
            - Path=/notifications/**
          filters:
            - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_FIRST
        - id: user
          uri: http://user:8080
          predicates:
            - Path=/users/**, 
        - id: dispatch
          uri: http://dispatch:8080
          predicates:
            - Path=/operations/**, /matchings/**, 
        - id: driver
          uri: http://driver:8080
          predicates:
            - Path=/drivers/**, 
        - id: operationstatistics
          uri: http://operationstatistics:8080
          predicates:
            - Path=/operationstatisticses/**
        - id: paymentpbcfe
          uri: http://paymentpbcfe:8080
          predicates:
            - Path=/paymentpbcfe/**, 
        - id: alarmpbcfe
          uri: http://alarmpbcfe:8080
          predicates:
            - Path=/alarmpbcfe/**, 
        - id: reviewpbcfe
          uri: http://reviewpbcfe:8080
          predicates:
            - Path=/reviewpbcfe/**, 
        - id: frontend
          uri: http://frontend:8080
          predicates:
            - Path=/**
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_FIRST
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            exposedHeaders:
              - "X-Total-Count"
              - "Link"
              - "Access-Control-Allow-Origin"
              - "Access-Control-Allow-Credentials"
            allowCredentials: true
            maxAge: 3600

server:
  port: 8080
